name: space_invaders
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flame: ^1.0.0
  flame_audio: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  ficcanaso: ^3.1.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
