name: space_invaders
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.0.0
  flame_audio: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flame_lint: ^0.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
